"""Legacy action vocabulary; execution and observations live in domain modules."""

ACTION_DESCRIPTIONS = {
    "prepare_patient_bed": "Place a verified safe temporary sleeping spot for a dependent patient with no reachable completed bed. Rescue and feeding are separate subsequent steps; placement alone does not feed or treat them.",
    "repair_architecture": "Restore missing parts of one observed partial building at its original site. Keep its selected material, orientation and doors; compare remaining cost and labor against urgent work. Occupied conflicts require a new decision, and no demolition is included.",
    "plan_architecture": "Choose a needed building program first, then let Laya select one procedurally generated, resource- and technology-aware layout. Housing alone provides 24 varied designs without storing 24 rigid blueprints.",
    "build_catalog_building": "Choose any currently unlocked and affordable building from RimWorld's live catalog, including DLC and modded definitions. Laya selects its category, exact building and compatible material; the game checks the site before an order is placed.",
    "build_research_bench": "Build the first affordable research bench so the colony can start research. Choose a compatible material from current stock; the game validates the site before placing its blueprint.",
    "improve_room_lighting": "Add a real light source to one dark high-value room selected by Laya; work rooms and hospital treatment should not operate in darkness.",
    "develop_colonist_skill": "Choose a colonist, skill and matching live WorkType using current level, small/large passion flames, learning traits, health and the colony's strategic gaps.",
    "optimize_night_owl_schedule": "Move one Night Owl colonist's sleep to 11:00-18:59 and leave the night flexible for work and recreation.",
    "schedule_recreation": "Give one stressed, recreation-starved colonist two protected Joy hours each day. This costs work time but can prevent an early mental break even before new furniture is ready.",
    "build_recreation_pin": "Build a ten-wood horseshoes pin near the shelter to add a different kind of recreation. It competes with urgent beds and walls for scarce wood.",
    "upgrade_workbench": "Build an unlocked successor workbench beside the old one; keep the old bench until the upgrade is completed so production never disappears mid-transition.",
    "unforbid_supplies": "Remove the red forbidden marks from landed supplies so colonists can eat, equip and haul them.",
    "equip_colonists": "Equip unarmed colonists with real nearby ranged weapons before a raid; otherwise even a small animal can close to melee range.",
    "rescue_downed_colonist": "Send a mobile colonist to carry a downed ally to a completed bed; bleeding and starvation can kill while the colony waits.",
    "rescue_neutral_arrival": "Carry a downed non-hostile visitor to a completed bed. They may later ask to join, but rescue is not guaranteed recruitment; food, care and labor are costs.",
    "tend_colonist": "Send an available doctor directly to an injured colonist with an untreated wound or active bleeding, even when no bed exists.",
    "create_food_stockpile": "Place a temporary food-only stockpile near, but outside, the first bedroom; a proper freezer can replace it later.",
    "build_sleeping_spots": "Place free sleeping spots for colonists, using an empty roofed room when one is available; these cannot waste scarce materials in botched attempts.",
    "build_basic_beds": "Build a real bed inside an already completed roofed room. Outdoor sleeping spots are temporary; an outdoor bed wastes material and still leaves the sleeper exposed.",
    "build_campfire": "Build a 20-wood campfire near the house for immediate cooking. It burns out after a few days and is not a permanent clean kitchen.",
    "assign_real_bed": "Move a colonist sleeping outdoors or on a ground spot into an available completed indoor bed; this interrupts the current sleep but gives them a sheltered bed thereafter.",
    "prepare_emergency_medical_bed": "Mark a completed real bed for medical use now, so the wounded can rest properly without waiting for a new hospital.",
    "build_animal_spots": "Place free animal sleeping spots so injured colony animals can rest and receive treatment.",
    "rescue_downed_animal": "Carry a downed colony animal to a free completed animal sleeping place, even when it has no untreated wound.",
    "care_for_injured_animal": "Tend a colony animal only when a wound or disease is currently treatable; low health, pain, anesthesia and paralysis alone are not tend jobs.",
    "feed_hungry_animal": "Immediately feed the hungriest resting colony animal before starvation becomes critical.",
    "feed_hungry_colonist": "Immediately feed the hungriest downed colonist who cannot walk to available food.",
    "refuel_building": "Send an available hauler to refuel one completed cooler, cooking station or generator with existing fuel. A built but empty cooler cannot prevent heatstroke.",
    "eat_available_meal": "Send a mobile hungry colonist to eat an actual unlocked meal now. Other work can wait; delay risks malnutrition even when the colony owns food.",
    "create_nearby_food_cache": "Make a high-priority meal stockpile at the settlement because all available meals are far away; a hauler must then bring food within easy walking distance.",
    "open_sealed_food_store": "Meals are trapped inside a legacy freezer built without a door. Send a builder to deconstruct one exact wall tile; this restores food access without destroying the room.",
    "open_blocked_food_path": "A colonist is sealed behind walls or has repeatedly failed to reach food. Open one adjacent built wall before another meal order; leaving the pawn trapped can be fatal.",
    "finish_freezer_entrance": "Install a normal door in the repaired freezer entrance once the blocking wall is gone, preserving access and cooling.",
    "build_cemetery": "Create a real graveyard outside the living and food areas so human corpses can be buried normally.",
    "create_human_corpse_dump": "Create a critical-priority human-corpse dumping stockpile far outside colonist sight; this is faster than digging many graves.",
    "create_animal_corpse_dump": "Create a critical-priority animal-corpse stockpile beside the butcher area so carcasses are hauled and processed efficiently.",
    "build_butcher_spot": "Place a free butcher spot beside accessible animal carcasses and add its forever butchering bill. Hunting and hauling alone cannot turn carcasses into food.",
    "create_stone_chunk_dump": "Create a preferred stone-chunk dumping stockpile beside the stonecutter to remove long hauling trips.",
    "build_crematorium": "Build an electric crematorium and configure corpse cremation when power, steel, components and labor justify it.",
    "build_prison": "Prepare a small enclosed two-place prison before the next raid so Laya can capture and recruit a downed enemy; materials, food, medicine and guard labor are the costs.",
    "build_hospital": "Build a small enclosed two-bed clinic and later mark its completed beds medical.",
    "build_passive_cooler": "Install a 50-wood passive cooler in a hot occupied bedroom or clinic. Untreated heatstroke can kill even a fed, bandaged patient; the cooler needs wood refills and construction time.",
    "build_room_campfire": "Warm a cold occupied room with a 20-wood indoor campfire. It needs regular wood refills and can overheat a small room; without heat a hypothermic patient can die.",
    "build_room_heater": "Warm a cold occupied room with an electric heater (50 steel, one component, 175 W). It needs a working power connection; an unpowered heater will not rescue a patient.",
    "connect_room_heater_power": "Lay a checked conduit route from the live generator grid to an existing unpowered bedroom heater. The cable consumes steel and builder time before it can warm anyone.",
    "prioritize_thermal_project": "Choose an unfinished cooler or heater in a threatened patient's room and a capable builder. A blueprint alone changes no temperature; delaying construction can be fatal.",
    "configure_hospital_beds": "Mark the completed clinic beds as medical beds.",
    "floor_critical_room": "Floor a real shared bedroom, kitchen, food room or hospital chosen by Laya with an affordable material, balancing comfort, cleanliness, fire and reserves.",
    "build_pathways": "Build an affordable two-wide path between the colony core, stores and fields to improve routine movement speed.",
    "build_temple": "Build an Ideology-compatible ritual room around the colony's actual altar or ideogram precept, with no beds or work facilities.",
    "choose_colony_doctrine": "Choose or deliberately revise a persistent colony doctrine: settlement form/material, peaceful or aggressive posture, military investment, and production identity. Existing buildings are never replaced merely because the doctrine changes.",
    "build_private_bedroom": "Build one separate private bedroom in the current settlement material, improving sleep privacy and enabling an impressive-bedroom mood bonus without rebuilding existing rooms.",
    "excavate_mountain_bedroom": "Mine a compact bedroom into a verified solid natural-rock block, leaving natural rock walls and a one-cell entrance; furnish it only after excavation completes.",
    "finish_mountain_bedroom": "Furnish the already excavated mountain bedroom with a door, bed, light and climate control without replacing older housing.",
    "commission_sculptures": "Build or use an art bench and commission small sculptures so Laya can later place actual finished art in the highest-value room.",
    "install_sculpture": "Install one actual finished sculpture in a room selected by Laya: usually a shared dining/rec room, a weak bedroom, hospital, or long-duration workshop.",
    "build_weapon_shelves": "Build high-priority shelves for weapons and armor, protecting equipment from deterioration and removing loose-item beauty penalties.",
    "prioritize_armament": "Prioritize the doctrine's weapon or armor research and configure normal crafting bills when the required workshop and resources exist.",
    "build_animal_barn": "Build a temperature-aware animal barn with sleeping places and optional low-filth straw matting, preserving fire safety and hay reserves.",
    "build_animal_pen": "Build a finished fenced pen with a gate and marker before taming or buying livestock that can roam away.",
    "pause_late_sowing": "Disable sowing in existing outdoor growing zones when present temperature and remaining growing season make a harvest unlikely; existing mature crops remain harvestable.",
    "resume_seasonal_sowing": "Re-enable sowing when outdoor growing conditions become viable again.",
    "unforbid_corpses": "Remove forbidden marks from corpses so haulers can bury people and butcher usable animal carcasses.",
    "prioritize_burial": "Give Hauling priority 1 so exposed corpses are taken to graves or the butcher area.",
    "build_freezer": "Build a compact powered freezer around the food stockpile.",
    "create_stockpile": "Create an organized stockpile so materials are hauled into one known place.",
    "expand_stockpile": "Expand general storage because at least 90% of current stockpile cells are occupied.",
    "create_growing_zone": "Create a rice growing zone to establish renewable food production.",
    "build_starter_base": "Start a compact shared house on verified dry ground, with beds, a door and light. Enclose and roof it before spending its wood on optional floors or workstations.",
    "configure_food_bills": "Add sustainable simple-meal and butchering bills to completed work tables.",
    "rebalance_cooking": "Choose a real cook to assign or free from competing animal work when prepared meals are gone despite abundant edible ingredients.",
    "advance_research": "Select the next available project on the default route toward fabrication and starflight.",
    "advance_doctrine_research": "Let Laya choose one currently available research project whose live definition advances the selected economy, technology, defense or endgame direction.",
    "build_power": "Choose a power source from the live catalog, research a better source, or defer generation. Compare fuel, output, construction skill, grid demand and current consumers before placing a checked blueprint.",
    "connect_power_consumer": "Connect an existing unpowered device to the generator's actual electrical network with a continuous, checked conduit route.",
    "build_battery_shelter": "Enclose an existing outdoor battery under an automatic roof. Rain on an exposed battery can short the grid and start fires; a small shed costs about 70 wall material plus a door and builder time.",
    "build_hitech_lab": "Place blueprints for a hi-tech research bench and multi-analyzer.",
    "build_fabrication": "Place a fabrication bench needed for advanced components.",
    "build_ship": "Place a connected starter starship blueprint with reactor, engine, computer, sensor and cryptosleep caskets.",
    "income_drugs": "Adopt a psychoid cash-crop route: grow surplus psychoid, research drug production, and later make sale-only flake/yayo.",
    "income_tailoring": "Adopt a textile route: grow cotton and turn surplus textiles/leather into trade apparel.",
    "income_art": "Adopt an art route: build a sculptor table and make sale sculptures from renewable wood or stone.",
    "income_livestock": "Adopt an animal route: prioritize handling and sell surplus animals, wool, milk and leather without starving the herd.",
    "income_biofuel": "Adopt a chemfuel route: tame boomalopes when safe and refine surplus organics after Biofuel Refining.",
    "income_mining": "Adopt a mining route: mine local gold/silver first, then research long-range scanning for guarded resource expeditions.",
    "income_crops": "Adopt a low-tech surplus-crop route: grow corn after the emergency rice supply is secure and sell only the reserve above colony needs.",
    "income_brewing": "Adopt a beer route: grow hops, research brewing, make wort and ferment it into a durable trade product.",
    "income_travel_food": "Adopt a caravan-food route: make pemmican or packaged survival meals for sale and for longer trade expeditions.",
    "income_orbital": "Adopt an orbital trade route: research microelectronics and build a comms console plus beacon for passing ships.",
    "income_organs": "Adopt a prisoner-organ trade route, balancing doctor skill, medicine, surgery risk, ideology and colony mood against organ value.",
    "build_income_infrastructure": "Build the missing workshop for the chosen income strategy after its prerequisite research is complete.",
    "build_killbox": "Build an early open-path defensive funnel with cover and spike traps; it is only the outer layer, not the whole defense.",
    "build_fallback_defense": "Build an internal fallback firing line and melee choke so breachers, drop pods and infestations do not bypass every defense.",
    "build_turret_defense": "Add powered turrets with spaced cover after Gun Turrets research; colonists still provide the main firepower.",
    "build_mortar_post": "Add a protected mortar position after Mortars research to answer sieges and enemies waiting at the map edge.",
    "build_firefoam_defense": "Place firefoam coverage near power, fuel and the defensive line so incendiary raids do not destroy the colony.",
    "expand_home_area": "Expand Home area only around a threatened live fire so assigned firefighters can reach it; a remote wilderness fire may be left alone.",
    "start_stonecutting": "Research/build stonecutting and cut the stone type chosen by Laya from actual nearby chunks into fireproof blocks.",
    "start_taming": "Designate the exact nearby species and sex chosen by Laya for taming, considering handler skill and revenge risk.",
    "tame_wild_human": "A wild person can become a full colonist through ordinary taming when an Animals 7 handler is available. Review their health, proximity, food needs and the chance the attempt fails.",
    "breed_animals": "Keep a chosen adult male/female pair of the same tame species together and prioritize handling so they can reproduce naturally.",
    "plan_human_reproduction": "Choose an existing romantic couple and a reproductive approach only when food, housing and safety can support a child.",
    "process_mechanoids": "Research/build machining and add a bill to dismantle mechanoid corpses for useful materials.",
    "prepare_trade_caravan": "Prepare a guarded trade expedition to a friendly settlement, keeping enough defenders, food and medicine at home.",
    "prepare_trade_rations": "Unblock the chosen sale route: research pemmican, then cook enough travel rations at a real campfire or stove before sending a caravan.",
    "configure_income_production": "Configure the chosen workshop with a repeatable sale-goods bill while preserving survival reserves.",
    "prioritize_construction": "Give Construction priority 1 to the healthiest best builder so issued blueprints are completed.",
    "prioritize_construction_project": "Let Laya choose one exact unfinished blueprint/frame and a suitable builder, then issue a normal forced construction job.",
    "prioritize_firefighting": "Assign Firefighter priority 1 to every capable healthy colonist in one response while live flames threaten the Home area.",
    "prioritize_research": "Reserve one healthy researcher for the selected project: give Research priority 1 and move their ordinary priority-1 jobs to priority 2 while emergency duties stay available.",
    "prioritize_cooking": "Give Cooking priority 1 to a capable healthy cook while prepared meals are scarce.",
    "prioritize_growing": "Give Growing priority 1 to a capable healthy grower so crops are planted and harvested.",
    "harvest_local_plants": "Let Laya choose one real nearby mature wild plant type, then designate only those exact plants for harvesting.",
    "harvest_food_crops_early": "Harvest a selected batch of edible crops before full maturity when meals run low. This feeds the colony sooner but sacrifices some eventual yield; Laya chooses the crop and batch size.",
    "harvest_nearby_trees": "Cut a small group of nearby mature trees for wood when unfinished shelter and furniture cannot be built from empty stores.",
    "prioritize_hauling": "Give Hauling priority 1 so unlocked food reaches the protected food stockpile.",
    "prioritize_hunting": "Give Hunting priority 1 to the best healthy shooter.",
    "prioritize_handling": "Give Handling priority 1 so colony animals are fed, trained and managed.",
    "prioritize_plant_cutting": "Give Plant Cutting priority 1 for wood and wild-food gathering.",
    "prioritize_cleaning": "Give Cleaning priority 1 to reduce filth, infection and food poisoning risk.",
    "prioritize_rescue": "Give Basic priority 1 so a healthy colonist rescues downed allies before routine work.",
    "prioritize_doctor": "Give Doctor priority 1 so injuries are treated before routine work.",
    "designate_safe_hunting": "Let Laya choose one exact nearby animal using meat/leather/value, revenge risk and the colony's available fighters; thrumbos require a strong firing team.",
    "consider_dangerous_hunt": "Evaluate a dangerous wild animal separately from routine hunting. Laya chooses the target, then explicitly decides whether its likely revenge and combat power justify risking the colony now.",
    "leave_wildlife_alone": "Deliberately leave nearby valuable or dangerous wildlife alone when taming and hunting are not worth the present risk or workload.",
    "hold_survival": "Issue no new project while colonists eat, sleep, recover or finish already-issued survival work.",
    "select_research": "Choose any currently startable research project from the game's live technology tree, including modded projects.",
    "set_work_priority": "Choose a live work type, an eligible colonist and a priority from 1 to 4; the model decides the assignment.",
}

ACTION_LABELS = {
    "plan_architecture": "архитектурный проект",
    "build_catalog_building": "постройка из полного каталога",
    "connect_power_consumer": "подключить прибор к электросети",
    "build_research_bench": "первый исследовательский стол",
    "improve_room_lighting": "освещение комнаты",
    "develop_colonist_skill": "развитие навыка",
    "optimize_night_owl_schedule": "расписание совы",
    "schedule_recreation": "время для отдыха",
    "build_recreation_pin": "игра в подковы",
    "upgrade_workbench": "модернизация верстака",
    "unforbid_supplies": "разрешить припасы",
    "equip_colonists": "вооружить колонистов",
    "rescue_downed_colonist": "спасти упавшего колониста",
    "rescue_neutral_arrival": "спасти раненого гостя",
    "prepare_patient_bed": "подготовить безопасное место для пациента",
    "tend_colonist": "лечить раненого колониста",
    "create_food_stockpile": "пищевой склад",
    "build_sleeping_spots": "спальные места",
    "build_basic_beds": "обычные кровати",
    "build_campfire": "костёр для готовки",
    "assign_real_bed": "переселить в кровать",
    "prepare_emergency_medical_bed": "подготовить медицинскую кровать",
    "build_animal_spots": "лежанки животных",
    "rescue_downed_animal": "спасти лежачее животное",
    "care_for_injured_animal": "лечение животного",
    "feed_hungry_animal": "кормление животного",
    "feed_hungry_colonist": "кормление лежачего колониста",
    "refuel_building": "заправка постройки",
    "eat_available_meal": "отправить колониста поесть",
    "create_nearby_food_cache": "ближний склад еды",
    "open_sealed_food_store": "открыть запертый склад еды",
    "finish_freezer_entrance": "дверь пищевого склада",
    "build_cemetery": "кладбище",
    "create_human_corpse_dump": "дальняя свалка человеческих трупов",
    "create_animal_corpse_dump": "свалка туш у разделки",
    "build_butcher_spot": "место разделки животных",
    "create_stone_chunk_dump": "склад каменных глыб у камнетёса",
    "build_crematorium": "крематорий",
    "build_prison": "тюрьма",
    "build_hospital": "больница",
    "build_passive_cooler": "охладить жилую комнату",
    "build_room_campfire": "согреть комнату костром",
    "build_room_heater": "согреть комнату обогревателем",
    "connect_room_heater_power": "подключить обогреватель к сети",
    "prioritize_thermal_project": "срочно достроить обогрев или охлаждение",
    "configure_hospital_beds": "медицинские койки",
    "floor_critical_room": "пол в критической комнате",
    "build_pathways": "дорожки",
    "build_temple": "храм и ритуальная комната",
    "choose_colony_doctrine": "доктрина колонии",
    "build_private_bedroom": "отдельная спальня",
    "excavate_mountain_bedroom": "вырубить спальню в скале",
    "finish_mountain_bedroom": "обставить спальню в скале",
    "commission_sculptures": "заказать скульптуры",
    "install_sculpture": "поставить скульптуру",
    "build_weapon_shelves": "полки оружия и брони",
    "prioritize_armament": "оружие и броня",
    "build_animal_barn": "дом для животных",
    "build_animal_pen": "загон для животных",
    "pause_late_sowing": "остановить поздний посев",
    "resume_seasonal_sowing": "возобновить сезонный посев",
    "unforbid_corpses": "разрешить перенос трупов",
    "prioritize_burial": "захоронение и трупы",
    "build_freezer": "морозилка",
    "create_stockpile": "общий склад",
    "expand_stockpile": "расширение склада",
    "create_growing_zone": "рисовое поле",
    "build_starter_base": "жилой блок",
    "configure_food_bills": "рецепты еды",
    "rebalance_cooking": "время для готовки",
    "advance_research": "новое исследование",
    "advance_doctrine_research": "исследование по доктрине",
    "build_power": "электросеть",
    "build_battery_shelter": "крыша для батареи",
    "build_hitech_lab": "лаборатория",
    "build_fabrication": "станок компонентов",
    "build_ship": "космический корабль",
    "income_drugs": "доход: психоид",
    "income_tailoring": "доход: одежда",
    "income_art": "доход: скульптуры",
    "income_livestock": "доход: животные",
    "income_biofuel": "доход: химтопливо",
    "income_mining": "доход: ценные руды",
    "income_crops": "доход: излишки урожая",
    "income_brewing": "доход: пиво",
    "income_travel_food": "доход: дорожная еда",
    "income_orbital": "доход: орбитальная торговля",
    "income_organs": "доход: органы пленных",
    "build_income_infrastructure": "цех выбранного дохода",
    "build_killbox": "защитный коридор",
    "build_fallback_defense": "внутренняя линия обороны",
    "build_turret_defense": "турельная линия",
    "build_mortar_post": "миномётная позиция",
    "build_firefoam_defense": "противопожарная защита",
    "expand_home_area": "защитить дом от пожара",
    "start_stonecutting": "каменные блоки",
    "start_taming": "приручение животного",
    "tame_wild_human": "приручение дикого человека",
    "breed_animals": "разведение животных",
    "plan_human_reproduction": "планирование ребёнка",
    "process_mechanoids": "разбор механоидов",
    "prepare_trade_caravan": "торговая вылазка",
    "prepare_trade_rations": "пеммикан для торговли",
    "configure_income_production": "производство на продажу",
    "prioritize_construction": "строительство",
    "prioritize_construction_project": "приоритет конкретной постройки",
    "prioritize_firefighting": "тушение пожара",
    "prioritize_research": "исследования",
    "prioritize_cooking": "готовка",
    "prioritize_growing": "растениеводство",
    "prioritize_hauling": "переноска",
    "prioritize_hunting": "охота",
    "prioritize_handling": "животноводство",
    "prioritize_plant_cutting": "заготовка растений",
    "prioritize_cleaning": "уборка",
    "prioritize_rescue": "спасение раненых",
    "prioritize_doctor": "лечение",
    "designate_safe_hunting": "безопасная охота",
    "consider_dangerous_hunt": "рискованная охота",
    "leave_wildlife_alone": "оставить диких животных в покое",
    "harvest_local_plants": "сбор дикоросов",
    "harvest_food_crops_early": "ранний сбор урожая",
    "harvest_nearby_trees": "рубка деревьев для стройки",
    "open_blocked_food_path": "открыть путь к еде",
    "hold_survival": "наблюдать",
    "select_research": "выбрать исследование",
    "set_work_priority": "назначить приоритет работы",
}

ACTION_LABELS_EN = {
    "prepare_patient_bed": "Prepare a patient sleeping spot",
    "plan_architecture": "Design a building", "unforbid_supplies": "Unforbid supplies",
    "build_catalog_building": "Choose a catalog building",
    "connect_power_consumer": "Connect a powered device",
    "build_research_bench": "Build the first research bench",
    "equip_colonists": "Equip colonists", "rescue_downed_colonist": "Rescue a colonist",
    "rescue_neutral_arrival": "Rescue a visitor",
    "tend_colonist": "Tend a colonist",
    "create_food_stockpile": "Food stockpile", "build_sleeping_spots": "Sleeping spots",
    "build_basic_beds": "Beds", "build_animal_spots": "Animal sleeping spots",
    "build_campfire": "Cooking campfire",
    "assign_real_bed": "Assign a real bed", "prepare_emergency_medical_bed": "Make a medical bed",
    "schedule_recreation": "Schedule recreation", "build_recreation_pin": "Horseshoes pin",
    "rescue_downed_animal": "Rescue animal", "care_for_injured_animal": "Treat injured animal", "feed_hungry_animal": "Feed animal",
    "feed_hungry_colonist": "Feed colonist", "build_cemetery": "Cemetery",
    "eat_available_meal": "Eat a meal", "create_nearby_food_cache": "Nearby food cache",
    "open_sealed_food_store": "Open food store", "finish_freezer_entrance": "Food store door",
    "create_human_corpse_dump": "Human corpse dump", "create_animal_corpse_dump": "Animal corpse dump",
    "build_butcher_spot": "Butcher spot",
    "build_crematorium": "Crematorium", "build_prison": "Prison", "build_hospital": "Hospital",
    "build_passive_cooler": "Cool a patient room",
    "build_room_campfire": "Warm a room with a campfire",
    "build_room_heater": "Warm a room with a heater",
    "connect_room_heater_power": "Connect a bedroom heater",
    "prioritize_thermal_project": "Finish urgent temperature control",
    "choose_colony_doctrine": "Colony strategy", "build_private_bedroom": "Private bedroom",
    "build_freezer": "Freezer", "create_stockpile": "Stockpile", "expand_stockpile": "Expand stockpile",
    "create_growing_zone": "Growing zone", "build_starter_base": "Starter base",
    "build_killbox": "Defensive corridor", "build_fallback_defense": "Fallback defense",
    "expand_home_area": "Protect home from fire",
    "start_stonecutting": "Cut stone blocks", "start_taming": "Tame animal",
    "tame_wild_human": "Tame wild person",
    "build_animal_pen": "Build animal pen",
    "process_mechanoids": "Process mechanoids", "prepare_trade_caravan": "Trade caravan",
    "prepare_trade_rations": "Prepare trade rations",
    "prioritize_construction": "Prioritize construction", "prioritize_research": "Prioritize research",
    "prioritize_growing": "Prioritize growing", "prioritize_hauling": "Prioritize hauling",
    "prioritize_hunting": "Prioritize hunting", "prioritize_handling": "Prioritize animal handling",
    "prioritize_plant_cutting": "Prioritize plant cutting", "prioritize_cleaning": "Prioritize cleaning",
    "prioritize_rescue": "Prioritize rescue", "prioritize_doctor": "Prioritize medical care",
    "designate_safe_hunting": "Choose hunting target", "leave_wildlife_alone": "Leave wildlife alone",
    "consider_dangerous_hunt": "Risky hunt",
    "harvest_local_plants": "Harvest wild plants", "hold_survival": "Wait and observe",
    "harvest_food_crops_early": "Harvest food crops early",
    "rebalance_cooking": "Make time for cooking",
    "harvest_nearby_trees": "Cut nearby trees",
    "open_blocked_food_path": "Open food access",
    "select_research": "Choose research", "set_work_priority": "Set work priority",
    "prioritize_firefighting": "Fight the active fire",
}
