"""Offline coverage of installed QuestScriptDefs and actual tokenizer budgets.

Checks public XML rule text/inheritance and complete prompt transport, not native
quest generation, completion or Laya's strategic competence. Never contacts API.
"""
from __future__ import annotations
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import sys
import xml.etree.ElementTree as ET

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import colony_quests as quests


class AuditAgent:
    cfg = {"max_len": 512, "head_max_len": 192}
    def __init__(self):
        from tokenizers import Tokenizer
        paths = sorted((Path.home()/'.cache/huggingface/hub/models--convaiinnovations--laya/snapshots').glob('*/tokenizer/tokenizer.json'))
        if not paths:
            raise RuntimeError("Actual cached Laya tokenizer required")
        self.tokenizer = Tokenizer.from_file(str(paths[0]))
        self.seen = []
    def tok(self, text, **kwargs):
        return {"input_ids": self.tokenizer.encode(text, add_special_tokens=False).ids}
    def predict(self, state, questions):
        self.seen.append(state)
        key, question = next(iter(questions.items()))
        return {"answers": {key: {"choice": next(iter(question["criteria"]))}}}


def definitions(data: Path):
    nodes = []
    parents = {}
    for path in sorted(data.glob('*/Defs/QuestScriptDefs/**/*.xml')):
        for node in ET.parse(path).getroot().findall('QuestScriptDef'):
            nodes.append((path, node))
            if node.get('Name'): parents[node.get('Name')] = node
    def inherited(node, key):
        seen = set()
        while node is not None:
            found = node.find(key)
            if found is not None: return found
            parent = node.get('ParentName')
            if not parent or parent in seen: return None
            seen.add(parent)
            node = parents.get(parent)
        return None
    for path, node in nodes:
        name = node.findtext('defName')
        if not name: continue
        rules = []
        for key in ('questNameRules', 'questDescriptionRules', 'questDescriptionAndNameRules'):
            block = inherited(node, key)
            if block is not None:
                rules += [r.text or '' for r in block.findall('.//rulesStrings/li')]
        root = inherited(node, 'root')
        auto = inherited(node, 'autoAccept')
        yield {"quest_def": name, "pack": path.relative_to(data).parts[0],
               "source": str(path), "root": root.get('Class') if root is not None else None,
               "auto_accept": auto is not None and (auto.text or '').lower() == 'true',
               "rules": rules}


def audit(data):
    agent = AuditAgent()
    snapshot = {"map": {"resources": {"food": 0, "meals": 0, "medicine": 0}, "enemies": 0},
                "colonists": [{"id": 1, "downed": True, "bleeding_rate": 3.65, "hunger": 0}],
                "development": {}}
    results = []
    for index, source in enumerate(definitions(data)):
        offer = {"id": index, "quest_def": source['quest_def'], "name": source['quest_def'],
                 "description": '\n'.join(source['rules']) or 'Description is generated by the native quest root; hidden outcomes remain unknown.',
                 "state": "NotYetAccepted", "can_accept": True, "expiry_hours": 24,
                 "reward_groups": [], "requires_accepter": False, "offer_version": "offline-template-fixture"}
        fields = quests.offer_fields(offer, snapshot, {"endgame": "imperial_ascension"})
        pages = quests.review_pages(agent, offer, snapshot, {"endgame": "imperial_ascension"})
        for field, value in fields:
            actual = quests.reconstruct_field(pages, field)
            assert actual == quests.public_text(value), (source['quest_def'], field)
        assert all(quests._size(agent, p) <= 312 and p['colony']['bleeding'] == 3.65
                   and p['colony']['food'] == 0 and p['ending'] == 'imperial_ascension' for p in pages)
        results.append({k: v for k, v in source.items() if k != 'rules'} | {
            "public_rule_count": len(source['rules']), "pages": len(pages),
            "max_state_tokens": max(quests._size(agent, p) for p in pages),
            "all_fields_reconstructed": True,
            "description_sha256": hashlib.sha256(offer['description'].encode()).hexdigest(),
            "needs_runtime_generated_description": not bool(source['rules'])})
    if not results: raise RuntimeError("No installed quest definitions found")
    return {"scripts": len(results), "packs": dict(Counter(r['pack'] for r in results)),
            "all_prompt_fields_complete": True, "max_state_tokens": max(r['max_state_tokens'] for r in results),
            "game_started": False, "api_contacted": False, "model_inference": False,
            "scope": "Installed named scripts including utilities; XML templates are not generated live quests.",
            "quests": results}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--game-data', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    result = audit(args.game_data)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(result, ensure_ascii=False, indent=2), encoding='utf-8')
    print(json.dumps({k: v for k, v in result.items() if k != 'quests'}, ensure_ascii=False))


if __name__ == '__main__': main()
